INSERT INTO books (external_id, title, cover_url) VALUES
(1, 'Pride and Prejudice', 'https://covers.openlibrary.org/b/id/7984916-L.jpg'),
(2, 'Moby Dick', 'https://covers.openlibrary.org/b/id/7222246-L.jpg'),
(3, 'Frankenstein', 'https://covers.openlibrary.org/b/id/7222261-L.jpg'),
(4, 'The Adventures of Sherlock Holmes', 'https://covers.openlibrary.org/b/id/7222255-L.jpg'),
(5, 'Dracula', 'https://covers.openlibrary.org/b/id/7222231-L.jpg'),
(6, 'Alice''s Adventures in Wonderland', 'https://covers.openlibrary.org/b/id/7222241-L.jpg'),
(7, 'The Picture of Dorian Gray', 'https://covers.openlibrary.org/b/id/7222243-L.jpg'),
(8, 'The War of the Worlds', 'https://covers.openlibrary.org/b/id/7222245-L.jpg'),
(9, 'The Scarlet Letter', 'https://covers.openlibrary.org/b/id/7222247-L.jpg'),
(10, 'A Tale of Two Cities', 'https://covers.openlibrary.org/b/id/7222249-L.jpg'),
(11, 'Crime and Punishment', 'https://covers.openlibrary.org/b/id/7222250-L.jpg'),
(12, 'Great Expectations', 'https://covers.openlibrary.org/b/id/7222251-L.jpg'),
(13, 'Les Misérables', 'https://covers.openlibrary.org/b/id/7222252-L.jpg'),
(14, 'The Count of Monte Cristo', 'https://covers.openlibrary.org/b/id/7222253-L.jpg'),
(15, 'The Call of the Wild', 'https://covers.openlibrary.org/b/id/7222254-L.jpg'),
(16, 'Jane Eyre', 'https://covers.openlibrary.org/b/id/7222256-L.jpg'),
(17, 'Wuthering Heights', 'https://covers.openlibrary.org/b/id/7222257-L.jpg'),
(18, 'Heart of Darkness', 'https://covers.openlibrary.org/b/id/7222258-L.jpg'),
(19, 'The Hunchback of Notre-Dame', 'https://covers.openlibrary.org/b/id/7222259-L.jpg'),
(20, 'The Three Musketeers', 'https://covers.openlibrary.org/b/id/7222260-L.jpg'),
(21, 'The Brothers Karamazov', 'https://covers.openlibrary.org/b/id/7222262-L.jpg'),
(22, 'The Metamorphosis', 'https://covers.openlibrary.org/b/id/7222263-L.jpg'),
(23, 'War and Peace', 'https://covers.openlibrary.org/b/id/7222264-L.jpg'),
(24, 'Anna Karenina', 'https://covers.openlibrary.org/b/id/7222265-L.jpg'),
(25, 'Ulysses', 'https://covers.openlibrary.org/b/id/7222266-L.jpg'),
(26, 'Don Quixote', 'https://covers.openlibrary.org/b/id/7222267-L.jpg'),
(27, 'Madame Bovary', 'https://covers.openlibrary.org/b/id/7222268-L.jpg'),
(28, 'The Odyssey', 'https://covers.openlibrary.org/b/id/7222269-L.jpg'),
(29, 'The Iliad', 'https://covers.openlibrary.org/b/id/7222270-L.jpg'),
(30, 'Gulliver''s Travels', 'https://covers.openlibrary.org/b/id/7222271-L.jpg'),
(31, 'Robinson Crusoe', 'https://covers.openlibrary.org/b/id/7222272-L.jpg'),
(32, 'Treasure Island', 'https://covers.openlibrary.org/b/id/7222273-L.jpg'),
(33, 'The Jungle Book', 'https://covers.openlibrary.org/b/id/7222274-L.jpg'),
(34, 'Peter Pan', 'https://covers.openlibrary.org/b/id/7222275-L.jpg'),
(35, 'The Strange Case of Dr Jekyll and Mr Hyde', 'https://covers.openlibrary.org/b/id/7222276-L.jpg'),
(36, '20,000 Leagues Under the Sea', 'https://covers.openlibrary.org/b/id/7222277-L.jpg'),
(37, 'Around the World in Eighty Days', 'https://covers.openlibrary.org/b/id/7222278-L.jpg'),
(38, 'Journey to the Center of the Earth', 'https://covers.openlibrary.org/b/id/7222279-L.jpg'),
(39, 'The Time Machine', 'https://covers.openlibrary.org/b/id/7222280-L.jpg'),
(40, 'The Invisible Man', 'https://covers.openlibrary.org/b/id/7222281-L.jpg'),
(41, 'David Copperfield', 'https://covers.openlibrary.org/b/id/7222282-L.jpg'),
(42, 'Oliver Twist', 'https://covers.openlibrary.org/b/id/7222283-L.jpg'),
(43, 'The Man in the Iron Mask', 'https://covers.openlibrary.org/b/id/7222284-L.jpg'),
(44, 'The Prince and the Pauper', 'https://covers.openlibrary.org/b/id/7222285-L.jpg'),
(45, 'A Connecticut Yankee in King Arthur''s Court', 'https://covers.openlibrary.org/b/id/7222286-L.jpg'),
(46, 'Uncle Tom''s Cabin', 'https://covers.openlibrary.org/b/id/7222287-L.jpg'),
(47, 'The Adventures of Huckleberry Finn', 'https://covers.openlibrary.org/b/id/7222288-L.jpg'),
(48, 'The Adventures of Tom Sawyer', 'https://covers.openlibrary.org/b/id/7222289-L.jpg'),
(49, 'Sense and Sensibility', 'https://covers.openlibrary.org/b/id/7222290-L.jpg'),
(50, 'Emma', 'https://covers.openlibrary.org/b/id/7222291-L.jpg');


INSERT INTO authors (name, birth_year, death_year) VALUES
('Jane Austen', 1775, 1817),
('Herman Melville', 1819, 1891),
('Mary Shelley', 1797, 1851),
('Arthur Conan Doyle', 1859, 1930),
('Bram Stoker', 1847, 1912),
('Lewis Carroll', 1832, 1898),
('Oscar Wilde', 1854, 1900),
('H.G. Wells', 1866, 1946),
('Nathaniel Hawthorne', 1804, 1864),
('Charles Dickens', 1812, 1870),
('Fyodor Dostoevsky', 1821, 1881),
('Victor Hugo', 1802, 1885),
('Alexandre Dumas', 1802, 1870),
('Jack London', 1876, 1916),
('Charlotte Brontë', 1816, 1855),
('Emily Brontë', 1818, 1848),
('Joseph Conrad', 1857, 1924),
('Franz Kafka', 1883, 1924),
('Leo Tolstoy', 1828, 1910),
('James Joyce', 1882, 1941),
('Miguel de Cervantes', 1547, 1616),
('Gustave Flaubert', 1821, 1880),
('Homer', NULL, NULL),
('Jonathan Swift', 1667, 1745),
('Daniel Defoe', 1660, 1731),
('Robert Louis Stevenson', 1850, 1894),
('Rudyard Kipling', 1865, 1936),
('J.M. Barrie', 1860, 1937),
('Jules Verne', 1828, 1905),
('Mark Twain', 1835, 1910),
('Harriet Beecher Stowe', 1811, 1896);



INSERT INTO genres (name) VALUES
('Romance'),
('Adventure'),
('Science Fiction'),
('Mystery'),
('Horror'),
('Fantasy'),
('Classic'),
('Drama'),
('Historical'),
('Philosophy');


INSERT INTO book_authors (book_id, author_id) VALUES
((SELECT id FROM books WHERE external_id = 1), (SELECT id FROM authors WHERE name = 'Jane Austen')),
((SELECT id FROM books WHERE external_id = 2), (SELECT id FROM authors WHERE name = 'Herman Melville')),
((SELECT id FROM books WHERE external_id = 3), (SELECT id FROM authors WHERE name = 'Mary Shelley')),
((SELECT id FROM books WHERE external_id = 4), (SELECT id FROM authors WHERE name = 'Arthur Conan Doyle')),
((SELECT id FROM books WHERE external_id = 5), (SELECT id FROM authors WHERE name = 'Bram Stoker')),
((SELECT id FROM books WHERE external_id = 6), (SELECT id FROM authors WHERE name = 'Lewis Carroll')),
((SELECT id FROM books WHERE external_id = 7), (SELECT id FROM authors WHERE name = 'Oscar Wilde')),
((SELECT id FROM books WHERE external_id = 8), (SELECT id FROM authors WHERE name = 'H.G. Wells')),
((SELECT id FROM books WHERE external_id = 9), (SELECT id FROM authors WHERE name = 'Nathaniel Hawthorne')),
((SELECT id FROM books WHERE external_id = 10), (SELECT id FROM authors WHERE name = 'Charles Dickens')),
((SELECT id FROM books WHERE external_id = 11), (SELECT id FROM authors WHERE name = 'Fyodor Dostoevsky')),
((SELECT id FROM books WHERE external_id = 12), (SELECT id FROM authors WHERE name = 'Charles Dickens')),
((SELECT id FROM books WHERE external_id = 13), (SELECT id FROM authors WHERE name = 'Victor Hugo')),
((SELECT id FROM books WHERE external_id = 14), (SELECT id FROM authors WHERE name = 'Alexandre Dumas')),
((SELECT id FROM books WHERE external_id = 15), (SELECT id FROM authors WHERE name = 'Jack London')),
((SELECT id FROM books WHERE external_id = 16), (SELECT id FROM authors WHERE name = 'Charlotte Brontë')),
((SELECT id FROM books WHERE external_id = 17), (SELECT id FROM authors WHERE name = 'Emily Brontë')),
((SELECT id FROM books WHERE external_id = 18), (SELECT id FROM authors WHERE name = 'Joseph Conrad')),
((SELECT id FROM books WHERE external_id = 19), (SELECT id FROM authors WHERE name = 'Victor Hugo')),
((SELECT id FROM books WHERE external_id = 20), (SELECT id FROM authors WHERE name = 'Alexandre Dumas')),
((SELECT id FROM books WHERE external_id = 21), (SELECT id FROM authors WHERE name = 'Fyodor Dostoevsky')),
((SELECT id FROM books WHERE external_id = 22), (SELECT id FROM authors WHERE name = 'Franz Kafka')),
((SELECT id FROM books WHERE external_id = 23), (SELECT id FROM authors WHERE name = 'Leo Tolstoy')),
((SELECT id FROM books WHERE external_id = 24), (SELECT id FROM authors WHERE name = 'Leo Tolstoy')),
((SELECT id FROM books WHERE external_id = 25), (SELECT id FROM authors WHERE name = 'James Joyce')),
((SELECT id FROM books WHERE external_id = 26), (SELECT id FROM authors WHERE name = 'Miguel de Cervantes')),
((SELECT id FROM books WHERE external_id = 27), (SELECT id FROM authors WHERE name = 'Gustave Flaubert')),
((SELECT id FROM books WHERE external_id = 28), (SELECT id FROM authors WHERE name = 'Homer')),
((SELECT id FROM books WHERE external_id = 29), (SELECT id FROM authors WHERE name = 'Homer')),
((SELECT id FROM books WHERE external_id = 30), (SELECT id FROM authors WHERE name = 'Jonathan Swift')),
((SELECT id FROM books WHERE external_id = 31), (SELECT id FROM authors WHERE name = 'Daniel Defoe')),
((SELECT id FROM books WHERE external_id = 32), (SELECT id FROM authors WHERE name = 'Robert Louis Stevenson')),
((SELECT id FROM books WHERE external_id = 33), (SELECT id FROM authors WHERE name = 'Rudyard Kipling')),
((SELECT id FROM books WHERE external_id = 34), (SELECT id FROM authors WHERE name = 'J.M. Barrie')),
((SELECT id FROM books WHERE external_id = 35), (SELECT id FROM authors WHERE name = 'Robert Louis Stevenson')),
((SELECT id FROM books WHERE external_id = 36), (SELECT id FROM authors WHERE name = 'Jules Verne')),
((SELECT id FROM books WHERE external_id = 37), (SELECT id FROM authors WHERE name = 'Jules Verne')),
((SELECT id FROM books WHERE external_id = 38), (SELECT id FROM authors WHERE name = 'Jules Verne')),
((SELECT id FROM books WHERE external_id = 39), (SELECT id FROM authors WHERE name = 'H.G. Wells')),
((SELECT id FROM books WHERE external_id = 40), (SELECT id FROM authors WHERE name = 'H.G. Wells')),
((SELECT id FROM books WHERE external_id = 41), (SELECT id FROM authors WHERE name = 'Charles Dickens')),
((SELECT id FROM books WHERE external_id = 42), (SELECT id FROM authors WHERE name = 'Charles Dickens')),
((SELECT id FROM books WHERE external_id = 43), (SELECT id FROM authors WHERE name = 'Alexandre Dumas')),
((SELECT id FROM books WHERE external_id = 44), (SELECT id FROM authors WHERE name = 'Mark Twain')),
((SELECT id FROM books WHERE external_id = 45), (SELECT id FROM authors WHERE name = 'Mark Twain')),
((SELECT id FROM books WHERE external_id = 46), (SELECT id FROM authors WHERE name = 'Harriet Beecher Stowe')),
((SELECT id FROM books WHERE external_id = 47), (SELECT id FROM authors WHERE name = 'Mark Twain')),
((SELECT id FROM books WHERE external_id = 48), (SELECT id FROM authors WHERE name = 'Mark Twain')),
((SELECT id FROM books WHERE external_id = 49), (SELECT id FROM authors WHERE name = 'Jane Austen')),
((SELECT id FROM books WHERE external_id = 50), (SELECT id FROM authors WHERE name = 'Jane Austen'));



INSERT INTO book_genres (book_id, genre_id) VALUES
((SELECT id FROM books WHERE external_id = 1), (SELECT id FROM genres WHERE name = 'Romance')),
((SELECT id FROM books WHERE external_id = 2), (SELECT id FROM genres WHERE name = 'Adventure')),
((SELECT id FROM books WHERE external_id = 3), (SELECT id FROM genres WHERE name = 'Horror')),
((SELECT id FROM books WHERE external_id = 4), (SELECT id FROM genres WHERE name = 'Mystery')),
((SELECT id FROM books WHERE external_id = 5), (SELECT id FROM genres WHERE name = 'Horror')),
((SELECT id FROM books WHERE external_id = 6), (SELECT id FROM genres WHERE name = 'Fantasy')),
((SELECT id FROM books WHERE external_id = 7), (SELECT id FROM genres WHERE name = 'Classic')),
((SELECT id FROM books WHERE external_id = 8), (SELECT id FROM genres WHERE name = 'Science Fiction')),
((SELECT id FROM books WHERE external_id = 9), (SELECT id FROM genres WHERE name = 'Classic')),
((SELECT id FROM books WHERE external_id = 10), (SELECT id FROM genres WHERE name = 'Classic')),
((SELECT id FROM books WHERE external_id = 11), (SELECT id FROM genres WHERE name = 'Drama')),
((SELECT id FROM books WHERE external_id = 12), (SELECT id FROM genres WHERE name = 'Classic')),
((SELECT id FROM books WHERE external_id = 13), (SELECT id FROM genres WHERE name = 'Classic')),
((SELECT id FROM books WHERE external_id = 14), (SELECT id FROM genres WHERE name = 'Adventure')),
((SELECT id FROM books WHERE external_id = 15), (SELECT id FROM genres WHERE name = 'Adventure')),
((SELECT id FROM books WHERE external_id = 16), (SELECT id FROM genres WHERE name = 'Romance')),
((SELECT id FROM books WHERE external_id = 17), (SELECT id FROM genres WHERE name = 'Romance')),
((SELECT id FROM books WHERE external_id = 18), (SELECT id FROM genres WHERE name = 'Classic')),
((SELECT id FROM books WHERE external_id = 19), (SELECT id FROM genres WHERE name = 'Classic')),
((SELECT id FROM books WHERE external_id = 20), (SELECT id FROM genres WHERE name = 'Adventure')),
((SELECT id FROM books WHERE external_id = 21), (SELECT id FROM genres WHERE name = 'Philosophy')),
((SELECT id FROM books WHERE external_id = 22), (SELECT id FROM genres WHERE name = 'Classic')),
((SELECT id FROM books WHERE external_id = 23), (SELECT id FROM genres WHERE name = 'Classic')),
((SELECT id FROM books WHERE external_id = 24), (SELECT id FROM genres WHERE name = 'Romance')),
((SELECT id FROM books WHERE external_id = 25), (SELECT id FROM genres WHERE name = 'Classic')),
((SELECT id FROM books WHERE external_id = 26), (SELECT id FROM genres WHERE name = 'Adventure')),
((SELECT id FROM books WHERE external_id = 27), (SELECT id FROM genres WHERE name = 'Drama')),
((SELECT id FROM books WHERE external_id = 28), (SELECT id FROM genres WHERE name = 'Classic')),
((SELECT id FROM books WHERE external_id = 29), (SELECT id FROM genres WHERE name = 'Classic')),
((SELECT id FROM books WHERE external_id = 30), (SELECT id FROM genres WHERE name = 'Adventure')),
((SELECT id FROM books WHERE external_id = 31), (SELECT id FROM genres WHERE name = 'Adventure')),
((SELECT id FROM books WHERE external_id = 32), (SELECT id FROM genres WHERE name = 'Adventure')),
((SELECT id FROM books WHERE external_id = 33), (SELECT id FROM genres WHERE name = 'Fantasy')),
((SELECT id FROM books WHERE external_id = 34), (SELECT id FROM genres WHERE name = 'Fantasy')),
((SELECT id FROM books WHERE external_id = 35), (SELECT id FROM genres WHERE name = 'Horror')),
((SELECT id FROM books WHERE external_id = 36), (SELECT id FROM genres WHERE name = 'Science Fiction')),
((SELECT id FROM books WHERE external_id = 37), (SELECT id FROM genres WHERE name = 'Science Fiction')),
((SELECT id FROM books WHERE external_id = 38), (SELECT id FROM genres WHERE name = 'Science Fiction')),
((SELECT id FROM books WHERE external_id = 39), (SELECT id FROM genres WHERE name = 'Science Fiction')),
((SELECT id FROM books WHERE external_id = 40), (SELECT id FROM genres WHERE name = 'Science Fiction')),
((SELECT id FROM books WHERE external_id = 41), (SELECT id FROM genres WHERE name = 'Classic')),
((SELECT id FROM books WHERE external_id = 42), (SELECT id FROM genres WHERE name = 'Classic')),
((SELECT id FROM books WHERE external_id = 43), (SELECT id FROM genres WHERE name = 'Adventure')),
((SELECT id FROM books WHERE external_id = 44), (SELECT id FROM genres WHERE name = 'Adventure')),
((SELECT id FROM books WHERE external_id = 45), (SELECT id FROM genres WHERE name = 'Adventure')),
((SELECT id FROM books WHERE external_id = 46), (SELECT id FROM genres WHERE name = 'Classic')),
((SELECT id FROM books WHERE external_id = 47), (SELECT id FROM genres WHERE name = 'Adventure')),
((SELECT id FROM books WHERE external_id = 48), (SELECT id FROM genres WHERE name = 'Adventure')),
((SELECT id FROM books WHERE external_id = 49), (SELECT id FROM genres WHERE name = 'Romance')),
((SELECT id FROM books WHERE external_id = 50), (SELECT id FROM genres WHERE name = 'Romance'));
